fontSize: 24
words:
  - кот
  - собака
  - тигр
  - лев
  - олень
  - заяц
  - медведь
  - лиса
  - волк
  - енот
  - пингвин
  - акула
  - дельфин
  - кит
  - слон
  - жираф
  - зебра
  - обезьяна
  - человек
  - робот
  - книга
  - стол
  - стул
  - окно
  - дверь
  - лампа
  - программа
  - компьютер
  - клавиатура
  - экран
  - телефон
  - самолёт
  - поезд
  - машина
  - трактор
  - город
  - деревня
  - школа
  - библиотека
  - университет
  - музыка
  - картина
  - театр
  - кино
  - песня
  - танец

